### ISSUE TITLE
プルリクしてマージしてみよう　パート２

### ISSUE THREAD

**Issue by king-kazu39** [n0-izy/Exercise#2]
- [ ] ローカルでファイル追加（exercise.htmlなど）
- [ ] コミット
　※コミットメッセージは下記のようにしましょう。
```
> git commit -m "fix #2 コミットメッセージ"
```

コミットメッセージは間違えても修正ができるので大丈夫です。
下記コマンドでメッセージの修正ができます。
```
> git commit --amend -m "fix #1 exercise.html新規作成"
```

- [ ] プッシュ
　※ここまでできたらプルリクの仕方を教えるので連絡ください

- [ ] Githubでプルリクを出す。
- [ ] コードレビューして、承認されたらマスターにマージ

**Comment by n0-izy** [comment]
プッシュまで完了しました。
